# For and While loops

## Number series

Print the values of $1/n$ for $n \in [5, 10]$, each on a separate line. Use first a while loop, then try to use a for loop (which one is easier?). The output should look as follows: 

``` {python}
N = 10
for i in range(5, N + 1):
  print(f"1/{i} = {1/i:.3}") 
```

## Power series

Consider the approximation of Eulers constant $e = \sum_{n=0}^\infty \frac{1}{n!}$. Print the consecutive approximations where you only take the first $1, 2, 3, 4, ...$ terms into account and print each of them on a separate line to the console. Stop when the approximation only differs by $0.001$ or less from the real value of $e = 2.7183$ (make use of `math.e`, `math.factorial()`, and `math.fabs()`). The output should look as follows:

``` {python}
import math
dmin = 0.001
e = 0
i = 0
while math.e - e > dmin:
  e = e + 1 / math.factorial(i)
  print(f"Euler's e = {math.e:5.5} approximated to {i+1} terms = {e:5.5}") 
  i = i + 1
```

## Printing numbers (Spring 2025)

- Use a while loop to print the numbers from 1 to 10 to the screen. 
- Then use a for loop for the same task. Make use of the `range()` function for this.
- Finally, use a `for` loop to print the odd numbers from 1 to 10 to the screen.

``` {python}
#| echo: false
#| output: false
print("Print 1-10 using a while loop")
i = 0
while i < 11:
  i += 1
  print(i)

print("Print 1-10 using a for loop")
for i in range(1,11):
  print(i)

print("Print odd numbers 1-10 using a for loop")
for i in range(1,11,2):
  print(i)

```

As an example, the output of the last part should give:

``` {python}
#| echo: false
print("Print odd numbers 1-10 using a for loop")
for i in range(1,11,2):
  print(i)
```

## Decreasing series (Spring 2025)

- Use a `while` loop to print the terms of series $\sum_{n=1}^{\infty}\frac{1}{n^4}$ for which $\frac{1}{n^4} \geq 0.0001$.
- Repeat the same task but using a `for` loop (combine with a conditional statement). Remark that here the lazy evaluation of the `range()` function is also a benefit.

Output of either script should have following output:

``` {python}
#| echo: false
n = 1
t = 1 / n**4
while t > 0.0001:
  n += 1
  print(t)
  t = 1 / n**4
```

# Combining loops and conditional branching

## Prime numbers 

Prompt the user for a positive integer number $n$. Verify whether this number is prime (does not have any integer divisors except 1 and $n$). For this you can loop over all numbers $m \leq \sqrt{n}$ and check whether $n/m$ is a natural number. Use `math.sqrt()` for the square root and the modulo operator `%` which gives the rest after division (e.g. `13 % 5 = 3`) to verify whether $n$ can be divided by $m = 2, 3, 4, ...$. The output should look as follows:

``` {python}
from math import sqrt, floor

print("Give a positive integer n: 169")
N = 169
n_max = sqrt(N)
is_prime = True
for n in range(2, floor(n_max) + 1):
    if N % n == 0:
        print(f"The number {N} can be divided by {n}")
        is_prime = False

if is_prime:
    print(f"The number {N} is prime")
else:
    print(f"The number {N} is not prime")
```

## Play rock-paper-scissors

Prompt the player repetitively to choose from: [1] Rock , [2] Paper, [3] Scissors, or [4] Stop the game. Award points for winning (+1), losing (-1), or a draw (0). Use the function `randint(1, 3)` from package `random` to obtain random integers from the set $\{1, 2, 3\}$. Stop the script when the choice was 4. Example output:

```
--- Let's play Rock-Paper-Scissors ---
  [1] Rock , [2] Paper, [3] Scissors, or [4] Stop the game
Choose 1-4: 3
I had the same, score: 0

  [1] Rock , [2] Paper, [3] Scissors, or [4] Stop the game
Choose 1-4: 2
You lose, I had Scissors, score: -1

  [1] Rock , [2] Paper, [3] Scissors, or [4] Stop the game
Choose 1-4: 1
You win, I had Scissors, score: 0

  [1] Rock , [2] Paper, [3] Scissors, or [4] Stop the game
Choose 1-4: 4

Stopping game!
```

## Game of higher-lower (Spring 2025)

Create a simple version of the higher-lower game where a person thinks of a number and the other has to guess it. 
Generate a random number using following code:

``` {.python}
import random
n = random.randint(0, 100)
```

Afterwards, prompt the user repetitively to make a guess, 
and tell each time whether the number is higher or lower than the guess. 
If the user guesses the actual number, stop the game. See following example output of a correct working script:

```
Guess the number [0, 100]: game started!
What is the number? 45
The number is lower, try again.
What is the number? 10
The number is lower, try again.
What is the number? 4
The number is higher, try again.
What is the number? 7
Yes, that is the number! Congratulations, you guessed it in 4 guesses.
```
