## Create Numpy arrays (Spring 2025)

Unlike lists, *arrays* have a fixed length of elements, and all elements must 
have the same type (the elements of the array can be changed). We will use the 
Numpy package for arrays, **Numpy arrays are much faster** to access than lists. 

You can create Numpy arrays in various ways:

```{python}
#| echo: true
#| output: false
import numpy as np

a1 = np.array([4, 2, 1])  # a1 = array created from a "2D" list
print(f"a1 = {a1}")
a2 = np.zeros((3, 1))     # a2 = 3x1 array (row-vector) with zeros
print(f"a2 = {a2}")
a3 = np.ones((4, 2))      # a3 = 4x2 array filled with ones
print(f"a3 = {a3}")
a4 = np.eye(2)            # a4 = 2x2 Identity matrix
print(f"a4 = {a4}")
```

Perform the following tasks:

- Convert the list: `[1, 2, 3]` to an array using the `np.array()` method.
- Create an $3 \times 2$ array filled with zeros using `np.zeros(n, m)`, print the array.
- Create an $1 \times 5$ array filled with ones using `np.ones(n, m)`, print the array.

## Access elements in Numpy arrays (Spring 2025)

Accessing elements of arrays is done in the same manner.

```{python}
#| echo: true
# Get the 1th element of the array
i = 0
element = a1[i]
print(f"The element with index {i} = {element}")
```

Perform the following tasks:

- Create a $3\times 3$ array and fill the last column with numbers 1, 2, 3
- Extract the first row using the colon operator similar to lists
- Print the diagonal numbers using a loop

## Different ways to generate the x-values: with Numpy (Spring 2025)


- Create an array containing: `[1, 2, 3, 4, 5]`
- Create an array using `np.linspace(start, stop, step)` with 20 elements equally spaced in the interval $[-2, 1]$
- Create an array using `np.arange(start, stop, step)` with inter-element distance of 0.5 for the same interval $[-2, 1]$

## Element-wise operations with Numpy arrays (Spring 2025)

Numpy also provides element-wise operations on Numpy arrays. We can use this to 
generate for example y-coordinates:

```{python}
#| echo: true
# Numpy arrays provide element-wise operations
y = x1**2  #  y contains squared array elements
print(f"y = {y}")
z = 5 * x1 + 3  #  z contains elements of x multiplied by 5 and increased with 3
print(f"z = {z}")
```

Numpy also provides functions on Numpy arrays:

```{python}
#| echo: true
res = np.exp(a1)
print(res)
a_degrees = np.array([45, 60, 30, 180, 90])
rads = np.deg2rad(a_degrees)
y = np.cos(rads)
print(y)
```

- Create x and y coordinates for the expressions (take as interval $[-2, 2]$):

$$
\begin{aligned}
y &= x^3\\
y &= \sin(\pi x)\\
y &= \sqrt(x + 2)\\
y &= \frac{\sin(\pi x)}{x}\\
\end{aligned}
$$

## Expressions with Numpy arrays

Import the Numpy library and/or functions and take $x$ now an array in interval $[-2, 2]$. 

``` {python}
import numpy as np
import matplotlib.pyplot as plt 

x = np.linspace(-2, 2, 400)
y = x

fig, ax = plt.subplots()
ax.plot(x, y)
plt.show()
fig.savefig("my_plot_name.png")
```

Plot the following formulas:

$$
\begin{aligned}
y & = x^2  \\
y & = \frac{\sin(\pi\, x)}{x+5\pi} + 1  \\
y & = x^3 - 4 x^2 + 2 \\
y & = \Re\{\sqrt{x}\} \\
\end{aligned}
$$
