# Sequences: lists, ranges, tuples, strings

We already briefly saw lists, ranges, and strings before, these data types fall actually under a common denominator: the sequence. Sequences are **collections** of elements with an **order**. There are also **unordered collections** in Python: **sets**. The following types are typical sequences:

-   **`list`**: adaptable sequence of objects, 
-   **`range`**: sequence of integers, 
-   strings (**`str`**): fixed sequence of characters, 
-   **tuple**: a fixed sequence of objects, i.e. like a list but not adaptable,
-   ...

It is useful to know that these are all sequences because sequences have common operations: indexing, slicing, certain functions such as `len()`, and methods such as `.sort()`.

We can split sequences in two groups: those that are mutable (adaptable) and those that immutable (fixed). Mutability is actually an important concept and determines which of the above mentioned common operations can be applied. Before we look at common operations of sequences, let us have a closer look at mutability.

## Mutable versus Immutable

To understand what mutable means we first should appreciate that every object has a **unique ID** (in CPython this ID would be directly related to the address in memory). We can ask the ID of any Python object using the function `id()`, for example, an integer is an object and would have an ID:

```{python}
i = 45 
print(id(i))
```

Other objects also have ID's:

```{python}
a_string = "Pretzel"
a_list = [3, 105, 56]
a_range = range(4)
print(f"The ID of a_string: {a_string} = { id(a_string) }")
print(f"The ID of a_list: {a_list} = { id(a_list) }")
print(f"The ID of a_range: {a_range} = { id(a_range) }")
```

If an object is mutable, its content can change without changing its ID. In case an object is of immutable type, then the ID should change if the content changes. Let us take an integer number as example below. 

### Numbers are immutable 

Since numbers are immutable in Python, their ID should change if you change them. Even if you assign them again to the same variable name! We can easily check this with the `id()` function:

```{python}
i = 45 
print(id(i))
i = i + 1
print(id(i))
```

### Strings are immutable 

Strings (`str`) are immutable just as numbers. A typical consequence is that operations on strings will provide a copy, the original string remains untouched:

```{python}
A = "Pretzel"
B = A.upper()
print(f"String A: {A} is still the same as A: {A}")
print(f"String B: {B} is the uppercase version of A: {A}")
print(f"ID of B: {id(B)} is not equal to ID of A: {id(A)}")
```

However, if you assign the new adapted string to the old variable name: `A = A.upper()`, then you will not have access to the initial string anymore.

### Lists are mutable

Lists are mutable, their elements can change, added, removed, etc. Although the length of the list can change, the object will stay the same:

```{python}
a_list = [3, "car", 5]
print(a_list)
print(id(a_list))

# Change 2nd element
a_list[1] = "tree"
print(a_list)
print(id(a_list))
```

This has a consequence that whenever we adapt a list, we possibly lose the original elements. As an illustration of such side-effects, look at the following script, that calculates the median of a list of numbers.

```{python}
# Input list of numbers
numbers = [3, 4, 5, 2, 8, 1, 6, 7]

# Algorithm to find the median
numbers.sort()
n = len(numbers)
if (n % 2) == 1:
    m = numbers[int((n + 1) / 2)]
else:
    m = (numbers[int(n/2-1)] + numbers[int(n/2)]) / 2

# Output the results
print(f"The median of {numbers} is {m}")
```

Notice that the list is sorted after applying our approach to obtain the `median`, and we lost the original order of the list. This is a side-effect. We actually could avoid this by using the function `sorted()` that returns a copy instead of the method `sort()` that sorts the elements in-place:

```{python}
numbers_1 = [3, 4, 5, 2, 8, 1, 6, 7]
sorted_numbers = sorted(numbers_1)
print(f"sorted_numbers: {sorted_numbers}, but numbers_1: {numbers_1} has still original order" )
numbers_2 = [3, 4, 5, 2, 8, 1, 6, 7]
numbers_2.sort()
print(f"numbers_2 is sorted in place: {numbers_2}")
```

Let's rewrite our little median algorithm using the `sorted()` function (this is not a method but a function):

```{python}
# Input list of numbers
numbers = [3, 4, 5, 2, 8, 1, 6, 7]

# Algorithm to find the median
sorted_numbers = sorted(numbers)  # This line changed
n = len(numbers)
if (n % 2) == 1:
    m = numbers[int((n + 1) / 2)]
else:
    m = (numbers[int(n/2-1)] + numbers[int(n/2)]) / 2

# Output the results
print(f"The median of {numbers} is {m}")
```

There are other methods that work "in-place" such as `s.reverse()` (reverses the order of elements of sequence `s` in-place), which have an alternative function: `reversed(s)`, that return a changed copy instead. This allows us to choose to either return a copy, albeit with possible large memory overhead, or do the operation in-place thereby losing the initial elements. Whatever approach you prefer, it is important to know whether a method/function **returns** an adapted copy of the object or it **adapts the object in-place**.

Nevertheless, with a list you cannot be sure that it didn't get adapted without knowing what each step of the code exactly does.

## Tuples are immutable lists

In case you want to make sure that your elements don't change, you can use a `tuple` instead of a `list`. Tuples are similar to lists in everything except that you cannot change them. The syntax to create a tuple is also very similar, but round brackets `(` and `)` are used instead of square brackets `[` and `]`:

```{python}
t = (3, "leaf", False)
print(t)
```

We can also cast from another collection to tuple, e.g. from `list`:

```{python}
t = tuple([1, 3.23, 3, 5 + 6J])
print(t)
```

Tuples are immutable, trying to adapt them will lead to an error:

```{python}
t = tuple([1, 3.23, 3, 5 + 6J])
t[0] = 2
```

While methods such as `append()`, `remove()`, etc. will work on lists, they will not work on tuples.

So far we have seen 4 sequence types, where list is the only one which is mutable, list and tuple can both contain elements of different (mixed) types, see the table below.

| Type    | mutable | item type   |
|---------|---------|-------------|
| `list`  | yes     | mixed types |
| `tuple` | no      | mixed types |
| `range` | no      | integers    |
| `str`   | no      | characters  |

Sequence operations are available according to mutability and type.

## Common sequence operations

There are many sequence operations which can be applied to any type of sequence: lists, tuples, ranges, strings, etc. For example, verifying whether elements can be found in the sequence or not, or combining sequences by concatenation.

``` {.python code-line-numbers="1-1|2-2|3-3|4-4|-"}
<bool> = el in s         # --> True/False
<bool> = el not in s     # --> True/False
s = s1 + s2              # concatenate s1 and s2
s * n or n * s           # n times concatenation
```

Some examples are:

```{python code-line-numbers="1-1|2-2|3-3|4-4|-"}
print("a" in "Hallo")          # --> True/False
print(9 not in range(4, 10))   # --> True/False
print([100, 200] + [500, 20])  # concatenate s1 and s2
print(("cat", "dog") * 3)      # n times concatenation
```
:::

Notice that as an exception concatenation does not work for ranges, this is due to their lazy evaluation.

All sequences also allow you to select elements by indexing or slicing, and we can count or find specific elements.

``` python
el = s[i]                # Select element i
s = s[start:end+1:step]  # Slicing
n = s.count[<el>]        # Count elements
i = s.index[<el>]        # index first el
```

For example for a tuple:

```{python}
s = ("Malta", "Corsica", "Lesvos", "Malta"); print(s)
print(f"Third element of s: { s[2] }")
print(f"Slice of s: { s[1:] }")
print(f"'Malta' appears: { s.count('Malta') } times")
print(f"First index of 'Malta': { s.index('Malta') }")
```

But exactly the same would work for a list:

```{python}
s = ["Malta", "Corsica", "Lesvos", "Malta"]; print(s)
print(f"Third element of s: { s[2] }")
print(f"Slice of s: { s[1:] }")
print(f"'Malta' appears: { s.count('Malta') } times")
print(f"First index of 'Malta': { s.index('Malta') }")
```

And also for a string where its elements are the characters composing the string:

```{python}
s = "Malta and Corsica"; print(s)
print(f"Third element of s: { s[2] }")
print(f"Slice of s: { s[1:] }")
print(f"'a' appears: { s.count('a') } times")
print(f"First index of 'a': { s.index('a') }")
```



## Sequence operations: only mutable

List is the only mutable sequence so far and we saw already many of possible operations:

``` python
<list>[i] = <el>
<list>.remove(<el>)        # remove first <el>
<list>.insert(i, <el>)     # insert <el> at index i
<el> = <list>.pop(i)       # return <el> at i and remove
<list>.append(<el>)        # Or: <list> += <el>
<list>.extend(<iterable>)  # Or: <list> += <iterable>
<list>.sort()              # Sorts list in-place
<list>.reverse()           # Reverses list in-place
```

Examples of applying these operations on lists:

```{python}
fruits = ["banana", "orange", "pear", "peach"]
nuts = ("almond", "walnut")

fruits.remove("banana")    # remove first <el>
fruits.insert(0, "mango")  # insert <el> at index i
el = fruits.pop(3)         # return <el> at i and remove
print(f"We popped {el}")
fruits.append("mandarin")  # Or: <list> += <el>
fruits.extend(nuts)        # Or: <list> += <iterable>
fruits.sort()              # Sorts list in-place
fruits.reverse()           # Reverses list in-place
print(fruits)
```

## Sequence operations: also for immutable types

Items of immutable types cannot change $\Rightarrow$ return value

``` python
<list> = sorted(<collection>)  # Returns sorted
<iter> = reversed(<list>)      # Returns reversed
```

Examples:

```{python}
#| output-location: fragment
t = (3, 5, 7, 2, 1)
t_sort = sorted(t)   # Returns sorted
t_rev = reversed(t)  # Returns reversed
print(t)
print(t_sort)
print(list(t_rev))
```

## String specific operations

Strings are also sequences, but since characters and text play such an important role, the `str` data type has some specific methods on top of the common sequence operations to fulfill specific needs. Below we list some often used string specific methods.

Often in data tables we want to avoid extra spaces around the data, one can use the method `strip()` to remove unwanted surrounding characters (most often extra space/tab characters):

```{python}
print("   Some_extra spaces ")
print("   Some_extra spaces ".strip())
print("_Some text...".strip('.'))
```

Splitting of a string in multiple parts or combining strings. For example this could be splitting a sentence in words. When combining (concatenating) strings one could think of adding the extension to a file name:

```{python}
# Split and join strings
print("Split_on_underscore".split(sep="_"))
print( ".".join(["program", "exe"]) )
```

Another very common operation would be to search for a specific substring (word or letter combination) within a larger string. Think of the "Find & Replace" functionality in typical text editors:  

```{python}
print("Ha" in "Hallo")           # Verify whether "Ha" can be found     
print("Ball".startswith("Bar"))  # Verify whether the string starts with "Bar"
print("Bicycle".find("cyc"))     # Returns the start-index of substring "cyc"
print("Bicycle".index("cyc"))    # Same as find, returns ValueError upon failure 
```

Replacing words is another very common operation:

```{python}
print("I like oranges".replace("oranges", "apples"))
```

Other convenient methods are those which change the capitalization of characters. This can be for example useful to perform case-insensitive comparison of words:

```{python}
print("GOOD morning".lower())    
print("GOOD morning".upper())      
print("GOOD morning".capitalize()) 
print("GOOD morning".title())      
```

Lastly, each unicode character corresponds to a unique integer, translation between both can be of particular convenience when performing low-level interactions with the keyboard:

```{python}
print(chr(68))  # Convert int to Unicode character.
print(ord("A")) # Convert Unicode character to int.
```

There are more methods specific to strings, here we just listed the most used ones to give an impression of the possibilities.
